.\"
.\" Man page for dcraw (Raw Photo Decoder)
.\"
.\" Copyright (c) 2003 by David Coffin
.\"
.\" You may distribute without restriction.
.\"
.\" David Coffin
.\" cybercom dot net, user dcoffin
.\" http://www.cybercom.net/~dcoffin
.\"
.TH dcraw 1 "July 17, 2003"
.LO 1
.SH NAME
dcraw - convert raw digital photos to PPM format
.SH SYNOPSIS
.B dcraw
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
.B dcraw
converts a list of raw digital camera files to
.BR ppm (5)
format.  Dozens of cameras are supported, and new ones are
added as they reach the market.
.SH OPTIONS
.TP
.B -i
Identify files but don't decode them.
Exit status is 0 if
.B dcraw
can decode the last file, 1 if it can't.
.TP
.B -c
Write binary image data to standard output.  Not compatible
with Microsoft operating systems.
.TP
.B -o file
Write to the named file.  Without
.B -c
or
.BR -o ,
output goes to ".ppm" files in the same directory as the input
files.
.TP
.B -f
Interpolate RGB as four colors.  The default is to assume that
all green pixels are the same.  If even-row green pixels are
more sensitive to ultraviolet light than odd-row green pixels,
this difference causes a mesh pattern in the output.
.B -f
solves this problem with minimal loss of detail.
.TP
.B -d
Show the raw data as a grayscale image with no interpolation.
Good for photographing black-and-white documents.
.TP
.B -q
Use simple bilinear interpolation for quick results.  The
default is to use a slow, high-quality adaptive algorithm.
.TP
.B -g gamma
Specify the gamma value for eight-bit output.  Default is 0.8.
.TP
.B -b brightness
Specify the output brightness.  Default is 1.0.
.TP
.B -w
Use the camera's custom white-balance settings.  The default is
to use fixed daylight values, calculated from sample images.
.TP
.B -r red_mul -l blue_mul
After all other color adjustments, multiply the red and blue
channels by these values.  Default is 1.0.
.TP
.B -2
Write eight bits per color value with gamma correction and
automatic brightness adjustment.  Double the width or height
if necessary to correct the aspect ratio.  This is the default.
.TP
.B -4
Write sixteen bits per color value, with no gamma correction,
no brightness adjustment, and no changes to the aspect ratio.
.TP
.B -3
Same image as
.BR -4 ,
written in Adobe PhotoShop format.  File extension is ".psd".
.SH "SEE ALSO"
ppm(5), ppm2tiff(1), pnmtopng(1), gphoto2(1).
.SH BUGS
The
.B -w
option does not work with all cameras.
.P
No attempt is made to save camera settings or thumbnail images.
.P
Author stubbornly refuses to add more output formats.
.P
Don't expect
.B dcraw
to produce the same images as software provided by the camera
vendor.  Sometimes
.B dcraw
gives better results!
.SH TIPS
First raise the brightness if the highlights are too dark,
then lower the gamma if the lowlights are too dark.
.P
To balance the color, do
.RB \^" dcraw\ -q\ -g\ 1\ -b\ 0.5 \^"
and select a rectangle of something that you know is white.
Compute the average R, G, and B values for this area, then
set red_mul and blue_mul to G/R and G/B.
.SH AUTHOR
Written by David Coffin, now at cybercom dot net with username dcoffin
