.\"
.\" Man page for dcraw (Raw Photo Decoder)
.\"
.\" Copyright (c) 2005 by David Coffin
.\"
.\" You may distribute without restriction.
.\"
.\" David Coffin
.\" dcoffin a cybercom o net
.\" http://www.cybercom.net/~dcoffin
.\"
.TH dcraw 1 "February 26, 2005"
.LO 1
.SH NAME
dcraw - convert raw digital photos to PPM format
.SH SYNOPSIS
.B dcraw
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
.B dcraw
converts raw digital photos to
.BR ppm (5)
format.
.SH OPTIONS
.TP
.B -i
Identify files but don't decode them.
Exit status is 0 if
.B dcraw
can decode the last file, 1 if it can't.
.TP
.B -c
Write binary image data to standard output.
By default,
.B dcraw
creates files with a ".ppm" extension.
.TP
.B -v
Print verbose messages.  Default is to print only warnings and errors.
.TP
.B -d
Show the raw data as a grayscale image with no interpolation.
Good for photographing black-and-white documents.
.TP
.B -q
Use simple bilinear interpolation for quick results.  The
default is to use a slow, high-quality adaptive algorithm.
.TP
.B -h
Half-size the output image.  Instead of interpolating, reduce
each 2x2 block of sensors to one pixel.  Much faster than
.BR -q .
.TP
.B -f
Interpolate RGB as four colors.  This causes a slight loss
of detail, so use
.B -f
only if you see false 2x2 mesh patterns in blue sky.
.TP
.B -a
Automatic color balance.  The default is to use a fixed
color balance based on a white card photographed in sunlight.
.TP
.B -w
Use the color balance specified by the camera.
If this can't be found,
.B dcraw
prints a warning and reverts to the default.
.TP
.B -r red_mul -l blue_mul
Further adjust the color balance by multiplying the red and
blue channels by these values.  Both default to 1.0.
.TP
.B -b brightness
Change the output brightness.  Default is 1.0.
.TP
.B -n
By default,
.B dcraw
clips all colors to prevent pink hues in the highlights.
Combine this option with
.B -b 0.25
to leave the image data completely unclipped.
.TP
.B -m
Write raw camera colors to the output file.  By default,
.B dcraw
converts to sRGB colorspace.
.TP
.B -s
For cameras based on the Fuji Super CCD SR, use the secondary
sensors, in effect underexposing the image by four stops to
reveal detail in the highlights.  For all other cameras,
.B -s
is silently ignored.
.TP
.B -t [0-7]
Flip the output image.  The most common flips are 5
(90 degrees CCW) and 6 (90 degrees clockwise).  By default,
dcraw tries to use the flip specified by the camera.
.RB \^" -t\ 0 \^"
forces
.B dcraw
not to flip images.
.TP
.B -2
Write eight bits per color value with a 99th-percentile white
point and the standard 0.45 gamma curve.  Double the height if
necessary to correct the aspect ratio.  This is the default.
.TP
.B -4
Write sixteen bits per color value.  Output is linear with
input -- no white point, no gamma, same aspect ratio.
.TP
.B -3
Same image as
.BR -4 ,
written in Adobe PhotoShop format.  File extension is ".psd".
.SH "SEE ALSO"
ppm(5), ppm2tiff(1), pnmtotiff(1), pnmtopng(1), gphoto2(1).
.SH BUGS
The
.B -w
option does not work with many cameras.
.P
No attempt is made to save camera settings or thumbnail images.
.P
Author stubbornly refuses to add more output formats.
.P
Don't expect
.B dcraw
to produce the same images as software provided by the camera
vendor.  Sometimes
.B dcraw
gives better results!
.SH TIPS
To balance the color, do
.RB \^" dcraw\ -h\ -b\ 0.5 \^"
and select a rectangle of something that you know is white.
Compute the average R, G, and B values for this area, then
set red_mul and blue_mul to G/R and G/B.
.SH AUTHOR
Written by David Coffin, dcoffin a cybercom o net
