name: Distribution

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build artifact
      run: ./build.sh
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: dcraw-windows.zip