name: Distribution

on:
  workflow_dispatch:
  
jobs:

  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/setup-nasm@v1

    - name: Build artifact
      run: ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dcraw-macos.tgz
        path: dcraw.tgz