name: Distribution

on:
  workflow_dispatch:
  
jobs:

  build:
    strategy:
      matrix:
        platform: [ubuntu, macos]

    runs-on: ${{ matrix.platform }}-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/setup-nasm@v1

    - name: Build artifact
      run: ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dcraw-${{ matrix.platform }}.gz
        path: dcraw.gz